[package.metadata.fetch-source]
"syn::latest" = { git = "https://github.com/dtolnay/syn.git" }
"syn::1.0.0" = { tar = "https://github.com/dtolnay/syn/archive/refs/tags/1.0.0.tar.gz" }
"syn::tag::1.0.0" = { git = "https://github.com/dtolnay/syn.git", tag = "1.0.0" }
