name: Release Please

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: rust
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
